config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  resources :users do
    resources :categories
  end

  resources :categories do
    resources :tasks
  end

  resources :tasks do
    member do
      patch 'update_status'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy

  validates :title, presence: { message: "Please enter a title." }, uniqueness: { scope: :user_id }
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category

  validates :name, presence: { message: "Please enter a task." }
  validate :due_date_not_in_past, unless: :updating_status_complete?

  def due_date_not_in_past
    if due_date.present? && due_date < Date.today
      errors.add(:due_date, "Date can't be in the past.")
    end
  end

  def updating_status_complete?
    status_complete_changed? && !due_date_changed?
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories
  has_many :tasks, through: :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :set_category, only: [:edit, :update, :show, :destroy]

  def index
    @categories = @user.categories
  end

  def new
    @category = @user.categories.build
  end

  def create
    @category = @user.categories.build(category_params)
    if @category.save
      redirect_to category_path(@category), notice: "Category created successfully"
    else
      flash[:alert] = @category.errors[:title].join(", ")
      redirect_to new_category_path
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to user_category_path(@user, @category), notice: "Category was successfully updated."
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    @category.destroy
    redirect_to categories_path, notice: "Category was successfully deleted."
  end

  private

  def set_user
    @user = current_user
  end

  def set_category
    @category = @user.categories.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:title, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!

  def home
    @tasks_by_category = current_user.tasks.where(due_date: Date.today, status_complete: false)
      .includes(:category)
      .group_by(&:category)

    @start_date = Date.today.beginning_of_month
    @end_date = @start_date.end_of_month
    @tasks = current_user.tasks.where(due_date: @start_date..@end_date)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, except: [:update_status]
  before_action :set_task_update, only: [:update_status]
  before_action :set_task, only: [:edit, :update, :destroy]

  def new
    @task = Task.new
  end

  def create
    @task = @category.tasks.build(task_params)

    if @task.save
      redirect_to category_path(@category), notice: "Task was successfully created."
    else
      due_date_errors
      redirect_to new_task_path
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to category_path(@category), notice: "Task status updated successfully."
    else
      due_date_errors
      redirect_to edit_task_path
    end
  end

  def update_status
    if @task.update(task_params) && @task.status_complete
      flash[:notice] = "Wooh, good job!"
    end
    redirect_to request.referrer
  end

  def destroy
    @task.destroy
    redirect_back(fallback_location: root_path, notice: "Task was successfully deleted.")
  end

  private

  def set_category
    @category = current_user.categories.find(params[:category_id])
  end

  def set_task
    @task = @category.tasks.find(params[:id])
  end

  def set_task_update
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:name, :due_date, :status_complete)
  end

  def due_date_errors
    error_messages = []
    error_messages.concat(@task.errors[:name]) if @task.errors[:name].any?
    error_messages.concat(@task.errors[:due_date]) if @task.errors[:due_date].any?
    flash[:alert] = error_messages.join(", ")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def format_due_date(due_date)
    if due_date.nil?
      return 'No due date'
    end
    today = Date.today
    tomorrow = today + 1
    due = due_date

    if due == today
      'Due today'
    elsif due == tomorrow
      'Due tomorrow'
    elsif due > tomorrow && due <= getNextWeek(today)
      "Due on #{due.strftime('%A')}"
    elsif due.month == today.month && due.year == today.year
      "Due on #{due.strftime('%B %e')}"
    else
      "Due on #{due.strftime('%B %e, %Y')}"
    end
  end

  def getNextWeek(date)
    next_week = date + 7
    next_week
  end
end

app/views/categories/_categoriesLists.html.erb
<section class="section-categoriesLists">
  <h2 class="categoriesLists-title">
    <% if @categories.empty? %>
      No categories yet.
    <% else %>
      Categories
    <% end %>
  </h2>
  <div class="categoriesLists-titles-lists-container">
    <% @categories.each do |category| %>
      <%= link_to category_path(category), class: "categoriesLists-titles-lists" do %>
        <%= category.title %>
      <% end %>
    <% end %>
  </div>

  <%= link_to 'Add Category +', new_category_path, class:"category-add-button"  %>


</section>

app/views/categories/_form.html.erb
<section class="section-form-category">
  <div class="form-column">
    <%= form_with model: [@user, @category] do |form| %>
      <div>
        <label for="category_title" class="category_title">Title: </label>
        <%= form.text_field :title, class: "form-category-input" %>
      </div>
      <div>
        <label for="category_description" class="category_description">Description: </label>
        <%= form.text_area :description, class: "form-category-input-description" %>
      </div>
      <div class="form-buttons-category">
        <%= form.submit "Submit", class: "form-category-submit" %>
        <%= link_to "Back", :back, class: "form-category-back" %>
      </div>
    <% end %>
  </div>
</section>

app/views/categories/_showForm.html.erb
<section class="section-category-details">
  <% if @category.description.present? %>
    <div class="category-details-description">
      <label>Description: </label>
      <span><%= @category.description %></span>
    </div>
  <% end %>
<div class="category-details-buttons">
  <button class="category-details-edit-button">
    <%= link_to 'Edit', edit_category_path(@category) %>
  </button>
  <%= button_to "Delete", @category, class: "category-details-remove-button", method: :delete,
      data: { confirm: "Are you sure you want to delete this category?" } %>
</div>

</section>

app/views/categories/edit.html.erb
<%= stylesheet_link_tag "formCategory" %>
<div class="container-form-category">
  <h2 class="form-category-title"> Edit Category </h2>
  <%= render 'form' %>
<div>

app/views/categories/index.html.erb
<%= stylesheet_link_tag "categoriesLists" %>
<div class="container-categoriesLists">
  <%= render 'categoriesLists' %>
<div>

app/views/categories/new.html.erb
<%= stylesheet_link_tag "formCategory" %>
<div class="container-form-category">
  <h2 class="form-category-title"> New Category </h2>
  <%= render 'form' %>
<div>

app/views/categories/show.html.erb
<%= stylesheet_link_tag "categoryDetails" %>
<div class="container-category-details">
  <h2 class="category-details-title"><%= @category.title %> </h2>
  <%= render 'showForm' %>
<div>

<%= render partial: 'tasks/taskList', locals: { tasks: @category.tasks } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Planner App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "navigation" %>
    <%= stylesheet_link_tag "body" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="body">

  <nav>
    <ul>
      <div>
        <%= link_to(root_path, class: "logo-link") do %>
          <%= image_tag('planner_logo.png', alt: 'Logo', class: "logo-image") %>
        <% end %>

        <li class="align-right">
          <% if user_signed_in? %>
            <%= form_tag destroy_user_session_path, method: :delete, class: "logout-form" do %>
              <%= submit_tag 'LOGOUT', class: "invisible-button nav-link" %>
            <% end %>
          <% end %>
        </li>

        <li class="align-right <%= 'selected' if current_page?(categories_path) %>"><%= link_to 'CATEGORIES', categories_path %></li>
        <li class="align-right <%= 'selected' if current_page?(root_path) %>"><%= link_to 'HOME', root_path %></li>
      </div>
    </ul>
  </nav>

  <div class="notice-alert-container">
    <div class="notice"><%= notice %></div>
    <div class="alert"><%= alert %></div>
  </div>

  <%= yield %>

  </body>
</html>

app/views/pages/_calendar.html.erb
<% if @tasks.present? %>
  <div class="calendar-container">
    <table class="calendar">
      <thead>
        <tr>
          <th colspan="7" class="calendar-title">
            <%= @start_date.strftime("%B %Y") %>
          </th>
        </tr>
        <tr>
          <% weekdays = %w(Sun Mon Tue Wed Thu Fri Sat) %>
          <% weekdays.each do |weekday| %>
            <th class="calendar-day"><%= weekday %></th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% current_date = @start_date.beginning_of_month %>
        <% starting_day_of_week = current_date.strftime("%a") %>
        <% index = weekdays.index(starting_day_of_week) %>
        <% current_date -= index.days %>
        <% while current_date <= @end_date.end_of_month %>
          <tr>
            <% 7.times do %>
              <% if current_date < @start_date.beginning_of_month || current_date > @end_date.end_of_month %>
                <td class="calendar-cell"></td>
              <% else %>
                <% if current_date == Date.today %>
                  <td class="calendar-cell today">
                <% else %>
                  <td class="calendar-cell">
                <% end %>
                  <h3 class="calendar-date"><%= current_date.strftime("%d") %></h3>
                  <% tasks_for_date = @tasks.where(due_date: current_date) %>
                  <% if tasks_for_date.empty? %>
                    <p></p>
                  <% else %>
                    <ul class="tasks-list">
                      <% tasks_for_date.each do |task| %>
                        <li class="task">
                          <%= link_to "o " + task.name,  task.category, class: "bullet-calendar-task" %>
                        </li>
                      <% end %>
                    </ul>
                  <% end %>
                </td>
              <% end %>
              <% current_date += 1.day %>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/pages/_today.html.erb
<div class="container-homepage">
    <section class="section-today">
      <h2 class="today-title">
        <% if @tasks_by_category.empty? %>
          Hooray, no task for today! <br>
          <%= link_to 'Create Task Now', new_category_path, class: "category-add-button today-add-button" %>
        <% else %>
          Today's Tasks
        <% end %>
      </h2>
      <% @tasks_by_category.each do |category, tasks| %>
        <% tasks.each do |task| %>
          <div class="today-task">
            <div class="today-task-div">
                <%= form_with model: [category, task], url: update_status_task_path(task), local: true, data: { remote: true } do |form| %>
                  <%= form.check_box :status_complete, checked: task.status_complete, onchange: "this.form.submit();" %>
                  <%= form.submit "Update Task Status", style: "display: none;" %>
                <% end %>

                <%= link_to task.name, edit_category_task_path(category, task), class: "task-name-today-label" %>
                <span class="category-name-today">
                  |
                  <%= link_to category.title, category_path(category) %>
                  |
                </span>
                <%= button_to "Delete", category_task_path(category, task), method: :delete,
                    data: { confirm: "Are you sure you want to delete this task?" },
                    class: "today-task-delete-button" %>
            </div>
          </div>
        <% end %>
      <% end %>
    </section>
</div>

app/views/pages/home.html.erb
<%= stylesheet_link_tag "today" %>
<%= stylesheet_link_tag "calendar" %>
<%= render 'today' %>
<%= render partial: 'calendar', locals: { start_date: @start_date, end_date: @end_date, tasks: @tasks } %>

app/views/tasks/_formTask.html.erb
<section class="section-task-form">
  <%= form_with model: [@category, @task] do |form| %>
    <div class="task-column">
      <div>
        <label for="task_name" class="task-name">Task: </label>
        <%= form.text_field :name, class: "task-name-input" %>
      </div>
      <div>
        <label for="due_date" class="due-date">Due Date: </label>
        <%= form.date_field :due_date, class: "due-date-input" %>
      </div>
    </div>
    <div class="form-buttons-tasks">
      <%= form.submit "Submit", class: "task-submit-button" %>
      <%= link_to "Back", :back, class: "task-submit-back" %>
    </div>

  <% end %>
</section>

app/views/tasks/_taskList.html.erb
<%= stylesheet_link_tag "taskList" %>

<div class="task-list">
  <% if tasks.present? %>
    <h2 class="task-title">Tasks</h2>
    <% tasks.order(status_complete: :asc).each do |task| %>
      <div class="task-item">
        <%= form_with model: [@category, task], url: update_status_task_path(task), local: true, data: { remote: true }, class: "task-form" do |form| %>
          <%= form.check_box :status_complete, checked: task.status_complete, onchange: "this.form.submit();", class: "task-status-checkbox" %>
        <% end %>
        <%= link_to task.name, edit_category_task_path(@category, task), class: "task-name-link",
            style: "#{task.status_complete ? 'text-decoration: line-through; text-decoration-thickness: 2px;' : ''}" %>
        <span class="due-date-text"> | <%= format_due_date(task.due_date) %> | </span>
        <%= button_to "Remove", category_task_path(@category, task), method: :delete,
            data: { confirm: 'Are you sure you want to delete this task?' },
            class: "task-delete-button" %>
      </div>
    <% end %>
  <% else %>
    <div>
      <label class="no-tasks-label">No tasks found.</label>
    </div>
  <% end %>

  <button class="add-task-button">
    <%= link_to '+ New Task', new_category_task_path(@category) %>
  </button>
</div>

app/views/tasks/edit.html.erb
<%= stylesheet_link_tag "formTask" %>
<div class="container-task-form">
  <h2 class="container-task-title"><%= @category.title %>'s Edit Task </h2>
  <%= render 'formTask' %>
<div>

app/views/tasks/new.html.erb
<%= stylesheet_link_tag "formTask" %>
<div class="container-task-form">
  <h2 class="container-task-title"><%= @category.title %>'s New Task </h2>
  <%= render 'formTask' %>
<div>